import { z } from "zod";

import { ProfessionalStatus } from "./professional";

/**
 * Zod 4 schema for the `Professional` entity.
 *
 * Aligned to the Prisma `Professional` model + the flattened `User`
 * identity fields. The domain type is the read-side DTO; the data
 * layer builds it via `mapToEnrichedProfessional`.
 *
 * Field mapping (Prisma → domain):
 *   - `User.name`   → `fullName`
 *   - `User.email`  → `email`
 *   - `User.image`  → `image`  (optional)
 *   - `Professional.specialties` → `specialties` (string[])
 *   - `Professional.license`     → `license`     (optional)
 *   - `Professional.bio`         → `bio`         (optional)
 */
export const professionalSchema = z.object({
  id: z.uuid({ error: "Invalid UUID" }),
  organizationId: z.uuid({ error: "Invalid UUID" }),
  userId: z.uuid({ error: "Invalid UUID" }),
  fullName: z
    .string()
    .min(1, { error: "Full name must be 1-100 characters" })
    .max(100, { error: "Full name must be 1-100 characters" }),
  email: z.email({ error: "Invalid email format" }),
  image: z.url({ error: "Image must be a valid URL" }).optional(),
  specialties: z
    .array(
      z
        .string()
        .min(1, { error: "Each specialty must be 1-100 characters" })
        .max(100, { error: "Each specialty must be 1-100 characters" }),
    )
    .min(1, { error: "At least one specialty is required" })
    .max(10, { error: "Maximum 10 specialties" }),
  license: z
    .string()
    .max(50, { error: "License max 50 characters" })
    .optional(),
  bio: z
    .string()
    .max(1000, { error: "Bio max 1000 characters" })
    .optional(),
  status: z.enum([ProfessionalStatus.ACTIVE, ProfessionalStatus.INACTIVE], {
    error: "Invalid status",
  }),
  createdAt: z.date(),
  updatedAt: z.date(),
});

/**
 * Schema for creating a professional — strips server-managed fields
 * (id, organizationId, userId, image, timestamps) and runs in strict
 * mode so any unknown field fails validation.
 *
 * Caller responsibilities:
 *   - `organizationId` is injected from the session in the action layer.
 *   - `userId` is generated by the data layer's `$transaction` (creates
 *     the linked `User` row first).
 *   - `image` is set later via User update — not part of the initial
 *     creation payload.
 */
export const professionalDataSchema = professionalSchema
  .omit({
    id: true,
    organizationId: true,
    userId: true,
    image: true,
    createdAt: true,
    updatedAt: true,
  })
  .strict();

export type Professional = z.infer<typeof professionalSchema>;
export type ProfessionalData = z.infer<typeof professionalDataSchema>;
